{
  "openapi": "3.0.1",
  "info": {
    "title": "API Reference",
    "description": "Sentry Public API",
    "termsOfService": "http://sentry.io/terms/",
    "contact": {
      "email": "partners@sentry.io"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "v0"
  },
  "servers": [
    {
      "url": "https://sentry.io/"
    }
  ],
  "tags": [
    {
      "name": "Teams",
      "description": "Endpoints for teams",
      "externalDocs": {
        "description": "Found an error? Let us know.",
        "url": "https://github.com/getsentry/sentry-docs/issues/new/?title=API%20Documentation%20Error:%20/api/teams/&template=api_error_template.md"
      }
    }
  ],
  "paths": {
    "/api/0/organizations/{organization_slug}/teams/": {
      "get": {
        "tags": [
          "Teams"
        ],
        "description": "Returns a list of teams bound to a organization.",
        "operationId": "List an Organization's Teams",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization for which the teams should be listed.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "avatar": {
                        "type": "object",
                        "properties": {
                          "avatarType": {
                            "type": "string",
                            "example": "letter_avatar"
                          },
                          "avatarUuid": {
                            "type": "string",
                            "nullable": true,
                            "example": null
                          }
                        }
                      },
                      "dateCreated": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2018-11-06T21:20:08.115Z"
                      },
                      "hasAccess": {
                        "type": "boolean",
                        "example": true
                      },
                      "id": {
                        "type": "string",
                        "example": "3"
                      },
                      "isMember": {
                        "type": "boolean",
                        "example": true
                      },
                      "isPending": {
                        "type": "boolean",
                        "example": false
                      },
                      "memberCount": {
                        "type": "integer",
                        "format": "int64",
                        "example": 1
                      },
                      "organization": {
                        "type": "object",
                        "properties": {
                          "avatar": {
                            "type": "object",
                            "properties": {
                              "avatarType": {
                                "type": "string",
                                "example": "letter_avatar"
                              },
                              "avatarUuid": {
                                "type": "string",
                                "nullable": true,
                                "example": null
                              }
                            }
                          },
                          "dateCreated": {
                            "type": "string",
                            "format": "date-time",
                            "example": "2018-11-06T21:20:08.115Z"
                          },
                          "id": {
                            "type": "string",
                            "example": "3"
                          },
                          "isEarlyAdopter": {
                            "type": "boolean",
                            "example": false
                          },
                          "name": {
                            "type": "string",
                            "example": "The Interstellar Jurisdiction"
                          },
                          "require2FA": {
                            "type": "boolean",
                            "example": false
                          },
                          "slug": {
                            "type": "string",
                            "example": "the-interstellar-jurisdiction"
                          },
                          "status": {
                            "type": "object",
                            "properties": {
                              "id": {
                                "type": "string",
                                "example": "active"
                              },
                              "name": {
                                "type": "string",
                                "example": "active"
                              }
                            }
                          }
                        }
                      },
                      "name": {
                        "type": "string",
                        "example": "Ancient Gabelers"
                      },
                      "projects": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "avatar": {
                              "type": "object",
                              "properties": {
                                "avatarType": {
                                  "type": "string",
                                  "example": "letter_avatar"
                                },
                                "avatarUuid": {
                                  "type": "string",
                                  "nullable": true,
                                  "example": null
                                }
                              }
                            },
                            "color": {
                              "type": "string",
                              "example": "#bf5b3f"
                            },
                            "dateCreated": {
                              "type": "string",
                              "format": "date-time",
                              "example": "2018-11-06T21:19:58.536Z"
                            },
                            "features": {
                              "type": "array",
                              "example": [
                                "releases",
                                "sample-events",
                                "minidump",
                                "servicehooks",
                                "rate-limits",
                                "data-forwarding"
                              ],
                              "items": {
                                "type": "string"
                              }
                            },
                            "firstEvent": {
                              "type": "string",
                              "example": null,
                              "nullable": true
                            },
                            "hasAccess": {
                              "type": "boolean",
                              "example": true
                            },
                            "id": {
                              "type": "string",
                              "example": "4"
                            },
                            "isBookmarked": {
                              "type": "boolean",
                              "example": false
                            },
                            "isInternal": {
                              "type": "boolean",
                              "example": false
                            },
                            "isMember": {
                              "type": "boolean",
                              "example": true
                            },
                            "isPublic": {
                              "type": "boolean",
                              "example": false
                            },
                            "name": {
                              "type": "string",
                              "example": "Prime Mover"
                            },
                            "platform": {
                              "type": "string",
                              "nullable": true
                            },
                            "slug": {
                              "type": "string",
                              "example": "prime-mover"
                            },
                            "status": {
                              "type": "string",
                              "example": "active"
                            }
                          }
                        }
                      },
                      "slug": {
                        "type": "string",
                        "example": "ancient-gabelers"
                      }
                    }
                  }
                },
                "example": [
                  {
                    "avatar": {
                      "avatarType": "letter_avatar",
                      "avatarUuid": null
                    },
                    "dateCreated": "2018-11-06T21:20:08.115Z",
                    "hasAccess": true,
                    "id": "3",
                    "isMember": true,
                    "isPending": false,
                    "memberCount": 1,
                    "name": "Ancient Gabelers",
                    "projects": [],
                    "slug": "ancient-gabelers"
                  },
                  {
                    "avatar": {
                      "avatarType": "letter_avatar",
                      "avatarUuid": null
                    },
                    "dateCreated": "2018-11-06T21:19:55.114Z",
                    "hasAccess": true,
                    "id": "2",
                    "isMember": true,
                    "isPending": false,
                    "memberCount": 1,
                    "name": "Powerful Abolitionist",
                    "projects": [
                      {
                        "avatar": {
                          "avatarType": "letter_avatar",
                          "avatarUuid": null
                        },
                        "color": "#bf5b3f",
                        "dateCreated": "2018-11-06T21:19:58.536Z",
                        "features": [
                          "releases",
                          "sample-events",
                          "minidump",
                          "servicehooks",
                          "rate-limits",
                          "data-forwarding"
                        ],
                        "firstEvent": null,
                        "hasAccess": true,
                        "id": "3",
                        "isBookmarked": false,
                        "isInternal": false,
                        "isMember": true,
                        "isPublic": false,
                        "name": "Prime Mover",
                        "platform": null,
                        "slug": "prime-mover",
                        "status": "active"
                      },
                      {
                        "avatar": {
                          "avatarType": "letter_avatar",
                          "avatarUuid": null
                        },
                        "color": "#3fbf7f",
                        "dateCreated": "2018-11-06T21:19:55.121Z",
                        "features": [
                          "releases",
                          "sample-events",
                          "minidump",
                          "servicehooks",
                          "rate-limits",
                          "data-forwarding"
                        ],
                        "firstEvent": null,
                        "hasAccess": true,
                        "id": "2",
                        "isBookmarked": false,
                        "isInternal": false,
                        "isMember": true,
                        "isPublic": false,
                        "name": "Pump Station",
                        "platform": null,
                        "slug": "pump-station",
                        "status": "active"
                      },
                      {
                        "avatar": {
                          "avatarType": "letter_avatar",
                          "avatarUuid": null
                        },
                        "color": "#bf6e3f",
                        "dateCreated": "2018-11-06T21:20:08.064Z",
                        "features": [
                          "servicehooks",
                          "sample-events",
                          "data-forwarding",
                          "rate-limits",
                          "minidump"
                        ],
                        "firstEvent": null,
                        "hasAccess": true,
                        "id": "4",
                        "isBookmarked": false,
                        "isInternal": false,
                        "isMember": true,
                        "isPublic": false,
                        "name": "The Spoiled Yoghurt",
                        "platform": null,
                        "slug": "the-spoiled-yoghurt",
                        "status": "active"
                      }
                    ],
                    "slug": "powerful-abolitionist"
                  }
                ]
              }
            }
          },
          "403": {
            "description": "Forbidden"
          }
        },
        "security": [
          {
            "auth_token": [
              "team:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Teams"
        ],
        "description": "Create a new team bound to an organization. Only the name of the team is needed to create it, the slug can be auto generated.",
        "operationId": "Create a New Team",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization the team should be created for.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "required": [
                  "name"
                ],
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "The name of the team.",
                    "example": "Ancient Gabelers"
                  },
                  "slug": {
                    "type": "string",
                    "description": "The optional slug for this team. If not provided it will be auto generated from the name",
                    "example": "ancient-gabelers"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "avatar": {
                      "type": "object",
                      "properties": {
                        "avatarType": {
                          "type": "string",
                          "example": "letter_avatar"
                        },
                        "avatarUuid": {
                          "type": "string",
                          "nullable": true,
                          "example": null
                        }
                      }
                    },
                    "dateCreated": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2018-11-06T21:20:08.115Z"
                    },
                    "hasAccess": {
                      "type": "boolean",
                      "example": true
                    },
                    "id": {
                      "type": "string",
                      "example": "3"
                    },
                    "isMember": {
                      "type": "boolean",
                      "example": true
                    },
                    "isPending": {
                      "type": "boolean",
                      "example": false
                    },
                    "memberCount": {
                      "type": "integer",
                      "format": "int64",
                      "example": 1
                    },
                    "organization": {
                      "type": "object",
                      "properties": {
                        "avatar": {
                          "type": "object",
                          "properties": {
                            "avatarType": {
                              "type": "string",
                              "example": "letter_avatar"
                            },
                            "avatarUuid": {
                              "type": "string",
                              "nullable": true,
                              "example": null
                            }
                          }
                        },
                        "dateCreated": {
                          "type": "string",
                          "format": "date-time",
                          "example": "2018-11-06T21:20:08.115Z"
                        },
                        "id": {
                          "type": "string",
                          "example": "3"
                        },
                        "isEarlyAdopter": {
                          "type": "boolean",
                          "example": false
                        },
                        "name": {
                          "type": "string",
                          "example": "The Interstellar Jurisdiction"
                        },
                        "require2FA": {
                          "type": "boolean",
                          "example": false
                        },
                        "slug": {
                          "type": "string",
                          "example": "the-interstellar-jurisdiction"
                        },
                        "status": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string",
                              "example": "active"
                            },
                            "name": {
                              "type": "string",
                              "example": "active"
                            }
                          }
                        }
                      }
                    },
                    "name": {
                      "type": "string",
                      "example": "Ancient Gabelers"
                    },
                    "slug": {
                      "type": "string",
                      "example": "ancient-gabelers"
                    }
                  }
                },
                "example": {
                  "memberCount": 0,
                  "name": "Ancient Gabelers",
                  "isMember": false,
                  "hasAccess": true,
                  "isPending": false,
                  "dateCreated": "2020-08-19T21:46:47.877073Z",
                  "id": "542610",
                  "avatar": {
                    "avatarUuid": null,
                    "avatarType": "letter_avatar"
                  },
                  "slug": "ancient-gabelers"
                }
              }
            }
          },
          "400": {
            "description": "Bad input"
          },
          "403": {
            "description": "Forbidden"
          },
          "409": {
            "description": "Team slug already exists"
          }
        },
        "security": [
          {
            "auth_token": [
              "team:write"
            ]
          }
        ]
      }
    },
    "/api/0/teams/{organization_slug}/{team_slug}/": {
      "get": {
        "tags": [
          "Teams"
        ],
        "description": "Return details on an individual team.",
        "operationId": "Retrieve a Team",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization the team belongs to.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "team_slug",
            "in": "path",
            "description": "The slug of the team to get.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "avatar": {
                      "type": "object",
                      "properties": {
                        "avatarType": {
                          "type": "string",
                          "example": "letter_avatar"
                        },
                        "avatarUuid": {
                          "type": "string",
                          "nullable": true,
                          "example": null
                        }
                      }
                    },
                    "dateCreated": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2018-11-06T21:20:08.115Z"
                    },
                    "hasAccess": {
                      "type": "boolean",
                      "example": true
                    },
                    "id": {
                      "type": "string",
                      "example": "3"
                    },
                    "isMember": {
                      "type": "boolean",
                      "example": true
                    },
                    "isPending": {
                      "type": "boolean",
                      "example": false
                    },
                    "memberCount": {
                      "type": "integer",
                      "format": "int64",
                      "example": 1
                    },
                    "organization": {
                      "type": "object",
                      "properties": {
                        "avatar": {
                          "type": "object",
                          "properties": {
                            "avatarType": {
                              "type": "string",
                              "example": "letter_avatar"
                            },
                            "avatarUuid": {
                              "type": "string",
                              "nullable": true,
                              "example": null
                            }
                          }
                        },
                        "dateCreated": {
                          "type": "string",
                          "format": "date-time",
                          "example": "2018-11-06T21:20:08.115Z"
                        },
                        "id": {
                          "type": "string",
                          "example": "3"
                        },
                        "isEarlyAdopter": {
                          "type": "boolean",
                          "example": false
                        },
                        "name": {
                          "type": "string",
                          "example": "The Interstellar Jurisdiction"
                        },
                        "require2FA": {
                          "type": "boolean",
                          "example": false
                        },
                        "slug": {
                          "type": "string",
                          "example": "the-interstellar-jurisdiction"
                        },
                        "status": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string",
                              "example": "active"
                            },
                            "name": {
                              "type": "string",
                              "example": "active"
                            }
                          }
                        }
                      }
                    },
                    "name": {
                      "type": "string",
                      "example": "Ancient Gabelers"
                    },
                    "slug": {
                      "type": "string",
                      "example": "ancient-gabelers"
                    }
                  }
                },
                "example": {
                  "avatar": {
                    "avatarType": "letter_avatar",
                    "avatarUuid": null
                  },
                  "dateCreated": "2018-11-06T21:19:55.114Z",
                  "hasAccess": true,
                  "id": "2",
                  "isMember": true,
                  "isPending": false,
                  "memberCount": 1,
                  "name": "Powerful Abolitionist",
                  "organization": {
                    "avatar": {
                      "avatarType": "letter_avatar",
                      "avatarUuid": null
                    },
                    "dateCreated": "2018-11-06T21:19:55.101Z",
                    "id": "2",
                    "isEarlyAdopter": false,
                    "name": "The Interstellar Jurisdiction",
                    "require2FA": false,
                    "slug": "the-interstellar-jurisdiction",
                    "status": {
                      "id": "active",
                      "name": "active"
                    }
                  },
                  "slug": "powerful-abolitionist"
                }
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Team not found"
          }
        },
        "security": [
          {
            "auth_token": [
              "team:read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Teams"
        ],
        "description": "Update various attributes and configurable settings for the given team.",
        "operationId": "Update a Team",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization the team belongs to.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "team_slug",
            "in": "path",
            "description": "The slug of the team to get.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "required": [
                  "name"
                ],
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "The new name for the team.",
                    "example": "The Inflated Philosophers"
                  },
                  "slug": {
                    "type": "string",
                    "description": "A new slug for the team. It has to be unique and available.",
                    "example": "the-inflated-philosophers"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "avatar": {
                      "type": "object",
                      "properties": {
                        "avatarType": {
                          "type": "string",
                          "example": "letter_avatar"
                        },
                        "avatarUuid": {
                          "type": "string",
                          "nullable": true,
                          "example": null
                        }
                      }
                    },
                    "dateCreated": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2018-11-06T21:20:08.115Z"
                    },
                    "hasAccess": {
                      "type": "boolean",
                      "example": true
                    },
                    "id": {
                      "type": "string",
                      "example": "3"
                    },
                    "isMember": {
                      "type": "boolean",
                      "example": true
                    },
                    "isPending": {
                      "type": "boolean",
                      "example": false
                    },
                    "memberCount": {
                      "type": "integer",
                      "format": "int64",
                      "example": 1
                    },
                    "organization": {
                      "type": "object",
                      "properties": {
                        "avatar": {
                          "type": "object",
                          "properties": {
                            "avatarType": {
                              "type": "string",
                              "example": "letter_avatar"
                            },
                            "avatarUuid": {
                              "type": "string",
                              "nullable": true,
                              "example": null
                            }
                          }
                        },
                        "dateCreated": {
                          "type": "string",
                          "format": "date-time",
                          "example": "2018-11-06T21:20:08.115Z"
                        },
                        "id": {
                          "type": "string",
                          "example": "3"
                        },
                        "isEarlyAdopter": {
                          "type": "boolean",
                          "example": false
                        },
                        "name": {
                          "type": "string",
                          "example": "The Interstellar Jurisdiction"
                        },
                        "require2FA": {
                          "type": "boolean",
                          "example": false
                        },
                        "slug": {
                          "type": "string",
                          "example": "the-interstellar-jurisdiction"
                        },
                        "status": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string",
                              "example": "active"
                            },
                            "name": {
                              "type": "string",
                              "example": "active"
                            }
                          }
                        }
                      }
                    },
                    "name": {
                      "type": "string",
                      "example": "Ancient Gabelers"
                    },
                    "slug": {
                      "type": "string",
                      "example": "ancient-gabelers"
                    }
                  }
                },
                "example": {
                  "avatar": {
                    "avatarType": "letter_avatar"
                  },
                  "dateCreated": "2018-11-06T21:20:08.115Z",
                  "hasAccess": true,
                  "id": "3",
                  "isMember": false,
                  "isPending": false,
                  "memberCount": 1,
                  "name": "The Inflated Philosophers",
                  "slug": "the-inflated-philosophers"
                }
              }
            }
          },
          "400": {
            "description": "Bad Input"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Team not found"
          }
        },
        "security": [
          {
            "auth_token": [
              "team:write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Teams"
        ],
        "description": "Schedules a team for deletion.\n\nNote: Deletion happens asynchronously and therefor is not immediate. However once deletion has begun the state of a project changes and will be hidden from most public views.",
        "operationId": "Delete a Team",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization the team belongs to.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "team_slug",
            "in": "path",
            "description": "The slug of the team to get.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Success."
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Team not found"
          }
        },
        "security": [
          {
            "auth_token": [
              "team:admin"
            ]
          }
        ]
      }
    },
    "/api/0/teams/{organization_slug}/{team_slug}/projects/": {
      "get": {
        "tags": [
          "Teams"
        ],
        "description": "Return a list of projects bound to a team.",
        "operationId": "List a Team's Projects",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization the team belongs to.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "team_slug",
            "in": "path",
            "description": "The slug of the team to get.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "avatar": {
                        "type": "object",
                        "properties": {
                          "avatarType": {
                            "type": "string",
                            "example": "letter_avatar"
                          },
                          "avatarUuid": {
                            "type": "string",
                            "nullable": true,
                            "example": null
                          }
                        }
                      },
                      "color": {
                        "type": "string",
                        "example": "#bf5b3f"
                      },
                      "dateCreated": {
                        "type": "string",
                        "format": "date-time",
                        "example": "2018-11-06T21:19:58.536Z"
                      },
                      "features": {
                        "type": "array",
                        "example": [
                          "releases",
                          "sample-events",
                          "minidump",
                          "servicehooks",
                          "rate-limits",
                          "data-forwarding"
                        ],
                        "items": {
                          "type": "string"
                        }
                      },
                      "firstEvent": {
                        "type": "string",
                        "example": null,
                        "nullable": true
                      },
                      "hasAccess": {
                        "type": "boolean",
                        "example": true
                      },
                      "id": {
                        "type": "string",
                        "example": "4"
                      },
                      "isBookmarked": {
                        "type": "boolean",
                        "example": false
                      },
                      "isInternal": {
                        "type": "boolean",
                        "example": false
                      },
                      "isMember": {
                        "type": "boolean",
                        "example": true
                      },
                      "isPublic": {
                        "type": "boolean",
                        "example": false
                      },
                      "name": {
                        "type": "string",
                        "example": "Prime Mover"
                      },
                      "platform": {
                        "type": "string",
                        "nullable": true
                      },
                      "slug": {
                        "type": "string",
                        "example": "prime-mover"
                      },
                      "status": {
                        "type": "string",
                        "example": "active"
                      },
                      "team": {
                        "type": "object",
                        "properties": {
                          "id": {
                            "type": "string"
                          },
                          "name": {
                            "type": "string"
                          },
                          "slug": {
                            "type": "string"
                          }
                        }
                      },
                      "teams": {
                        "type": "array",
                        "items": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string"
                            },
                            "name": {
                              "type": "string"
                            },
                            "slug": {
                              "type": "string"
                            }
                          }
                        }
                      },
                      "latestDeploys": {
                        "type": "string",
                        "nullable": true
                      }
                    }
                  }
                },
                "example": [
                  {
                    "slug": "the-spoiled-yoghurt",
                    "name": "The Spoiled Yoghurt",
                    "hasAccess": true,
                    "teams": [
                      {
                        "id": "542609",
                        "name": "Powerful Abolitionist",
                        "slug": "powerful-abolitionist"
                      }
                    ],
                    "platform": null,
                    "firstEvent": null,
                    "isMember": false,
                    "team": {
                      "id": "542609",
                      "name": "Powerful Abolitionist",
                      "slug": "powerful-abolitionist"
                    },
                    "dateCreated": "2020-08-20T14:36:34.171255Z",
                    "isBookmarked": false,
                    "id": "5398494",
                    "latestDeploys": null,
                    "features": [
                      "custom-inbound-filters",
                      "discard-groups",
                      "rate-limits",
                      "data-forwarding",
                      "similarity-view",
                      "issue-alerts-targeting",
                      "servicehooks",
                      "minidump",
                      "similarity-indexing"
                    ]
                  }
                ]
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Team not found"
          }
        },
        "security": [
          {
            "auth_token": [
              "project:read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Teams"
        ],
        "description": "Create a new project bound to a team.",
        "operationId": "Create a New Project",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization the team belongs to.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "team_slug",
            "in": "path",
            "description": "The slug of the team to create a new project for.",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "required": [
                  "name"
                ],
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "The name for the new project.",
                    "example": "The Spoiled Yoghurt"
                  },
                  "slug": {
                    "type": "string",
                    "description": "Optionally a slug for the new project. If it’s not provided a slug is generated from the name.",
                    "example": "the-spoiled-yoghurt"
                  }
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "201": {
            "description": "Created.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "avatar": {
                      "type": "object",
                      "properties": {
                        "avatarType": {
                          "type": "string",
                          "example": "letter_avatar"
                        },
                        "avatarUuid": {
                          "type": "string",
                          "nullable": true,
                          "example": null
                        }
                      }
                    },
                    "color": {
                      "type": "string",
                      "example": "#bf5b3f"
                    },
                    "dateCreated": {
                      "type": "string",
                      "format": "date-time",
                      "example": "2018-11-06T21:19:58.536Z"
                    },
                    "features": {
                      "type": "array",
                      "example": [
                        "releases",
                        "sample-events",
                        "minidump",
                        "servicehooks",
                        "rate-limits",
                        "data-forwarding"
                      ],
                      "items": {
                        "type": "string"
                      }
                    },
                    "firstEvent": {
                      "type": "string",
                      "example": null,
                      "nullable": true
                    },
                    "hasAccess": {
                      "type": "boolean",
                      "example": true
                    },
                    "id": {
                      "type": "string",
                      "example": "4"
                    },
                    "isBookmarked": {
                      "type": "boolean",
                      "example": false
                    },
                    "isInternal": {
                      "type": "boolean",
                      "example": false
                    },
                    "isMember": {
                      "type": "boolean",
                      "example": true
                    },
                    "isPublic": {
                      "type": "boolean",
                      "example": false
                    },
                    "name": {
                      "type": "string",
                      "example": "Prime Mover"
                    },
                    "platform": {
                      "type": "string",
                      "nullable": true
                    },
                    "slug": {
                      "type": "string",
                      "example": "prime-mover"
                    },
                    "status": {
                      "type": "string",
                      "example": "active"
                    }
                  }
                },
                "example": {
                  "status": "active",
                  "name": "The Spoiled Yoghurt",
                  "color": "#bf6e3f",
                  "isInternal": false,
                  "isPublic": false,
                  "slug": "the-spoiled-yoghurt",
                  "platform": null,
                  "hasAccess": true,
                  "firstEvent": null,
                  "avatar": {
                    "avatarUuid": null,
                    "avatarType": "letter_avatar"
                  },
                  "isMember": false,
                  "dateCreated": "2020-08-20T14:36:34.171255Z",
                  "isBookmarked": false,
                  "id": "5398494",
                  "features": [
                    "custom-inbound-filters",
                    "discard-groups",
                    "rate-limits",
                    "data-forwarding",
                    "similarity-view",
                    "issue-alerts-targeting",
                    "servicehooks",
                    "minidump",
                    "similarity-indexing"
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Bad input"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Team not found"
          },
          "409": {
            "description": "Team already exists"
          }
        },
        "security": [
          {
            "auth_token": [
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/teams/{organization_slug}/{team_slug}/stats/": {
      "get": {
        "tags": [
          "Teams"
        ],
        "summary": "Caution\nThis endpoint may change in the future without notice.",
        "description": "Return a set of points representing a normalized timestamp and the number of events seen in the period.\n\nQuery ranges are limited to Sentry’s configured time-series resolutions.",
        "operationId": "Retrieve Event Counts for a Team",
        "parameters": [
          {
            "name": "organization_slug",
            "in": "path",
            "description": "The slug of the organization the team belongs to.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "team_slug",
            "in": "path",
            "description": "The slug of the team to get.",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "stat",
            "in": "query",
            "description": "the name of the stat to query `(\"received\", \"rejected\")`",
            "schema": {
              "type": "string",
              "enum": [
                "received",
                "rejected"
              ]
            }
          },
          {
            "name": "since",
            "in": "query",
            "description": "A timestamp to set the start of the query in seconds since UNIX epoch.",
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          },
          {
            "name": "until",
            "in": "query",
            "description": "A timestamp to set the end of the query in seconds since UNIX epoch.",
            "schema": {
              "type": "string",
              "format": "date-time"
            }
          },
          {
            "name": "resolution",
            "in": "query",
            "description": "An explicit resolution to search for (one of `10s`, `1h`, and `1d`).",
            "schema": {
              "type": "string",
              "enum": [
                "10s",
                "1h",
                "1d"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": [
                    [
                      1541455200,
                      3302
                    ],
                    [
                      1541458800,
                      3832
                    ],
                    [
                      1541462400,
                      3669
                    ],
                    [
                      1541466000,
                      3533
                    ],
                    [
                      1541469600,
                      3499
                    ],
                    [
                      1541473200,
                      3201
                    ],
                    [
                      1541476800,
                      3769
                    ],
                    [
                      1541480400,
                      2706
                    ],
                    [
                      1541484000,
                      2698
                    ],
                    [
                      1541487600,
                      3747
                    ],
                    [
                      1541491200,
                      3261
                    ],
                    [
                      1541494800,
                      2860
                    ],
                    [
                      1541498400,
                      4350
                    ],
                    [
                      1541502000,
                      2924
                    ],
                    [
                      1541505600,
                      3389
                    ],
                    [
                      1541509200,
                      2931
                    ],
                    [
                      1541512800,
                      3132
                    ],
                    [
                      1541516400,
                      3213
                    ],
                    [
                      1541520000,
                      3650
                    ],
                    [
                      1541523600,
                      3096
                    ],
                    [
                      1541527200,
                      3845
                    ],
                    [
                      1541530800,
                      3545
                    ],
                    [
                      1541534400,
                      2880
                    ],
                    [
                      1541538000,
                      4057
                    ]
                  ]
                }
              }
            }
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Team not found"
          }
        },
        "security": [
          {
            "auth_token": [
              "team:read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "auth_token": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  }
}
